package org.bukkit.loot;

import java.util.Collection;
import java.util.Random;
import org.bukkit.Keyed;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * 战利品表是技术性文件，用于表示自然生成的容器中应包含哪些物品、杀死生物时应掉落哪些物品，或者哪些物品可以通过钓鱼获得。
 * <br>
 * 更多信息请参见 <a href="https://minecraft.wiki/w/Loot_table">Minecraft Wiki</a>。
 */
public interface LootTable extends Keyed {

    /**
     * 返回由此战利品表生成的可变物品列表。
     * <p>
     * 原文：
     * Returns a mutable list of loot generated by this LootTable.
     *
     * @param random 用于生成战利品的随机实例
     * @param context 用于填充战利品的上下文
     * @return 物品栈列表
     */
    @NotNull
    Collection<ItemStack> populateLoot(@Nullable Random random, @NotNull LootContext context);

    /**
     * 尝试用此战利品表的战利品填充一个容器。
     * <p>
     * 原文：
     * Attempt to fill an inventory with this LootTable's loot.
     *
     * @param inventory 要填充的容器
     * @param random 用于生成战利品的随机实例
     * @param context 用于填充战利品的上下文
     */
    void fillInventory(@NotNull Inventory inventory, @Nullable Random random, @NotNull LootContext context);
}
